import type { Metadata } from "next";
import { Lato, Nunito } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

import { getUser as getUserData } from "@/services/user/userData";

const nunito = Nunito({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "TaskTO",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = getKindeServerSession();

  const user = await getUser();
  const userColorTheme = await getUserData(user?.id as string);
  return (
    <html lang="en">
      <body
        className={`${nunito.className} ${
          userColorTheme ? userColorTheme.colorTheme : "theme-blue"
        } `}
      >
        {" "}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
